### ISSUE TITLE
Plugin dont load...

### ISSUE THREAD

**Issue by Aromastoffe** [jasonwynn10/SpectreZone#1]
15:37:09 CRITICAL > TypeError: "Argument 1 passed to pocketmine\inventory\ShapedRecipe::__construct() must be of the type array, object given, called in /home/OziLobby/plugins/SpectreZone/src/jasonwynn10/SZ/SpectreZone.php on line 46" (EXCEPTION) in "src/pocketmine/inventory/ShapedRecipe" at line 57

IDK?!
pls help

**Comment by jasonw4331** [comment]
plugin not finished

**Comment by Aromastoffe** [comment]
aso okay :))
