### ISSUE TITLE
SpectreBlock and SpectreCoreBlock has infiniburn properties

### ISSUE THREAD

**Issue by JavierLeon9966** [jasonwynn10/SpectreZone#4]
Since they extend `Bedrock` they inherited all the properties including the infiniburn:

https://github.com/pmmp/PocketMine-MP/blob/7c3b78b0a0ae848a8fb034251ef53edb7b0c08e4/src/block/Bedrock.php#L28

**Comment by jasonw4331** [comment]
That's not a mistake
