### ISSUE TITLE
Block ID 5963776 is out of bounds

### ISSUE THREAD

**Issue by IvanCraft623** [jasonwynn10/SpectreZone#5]
This happens after using the Specter Key
Crashdump: https://crash.pmmp.io/view/6760492
This is a critical error as for inexperienced users it renders the server unusable.

**Comment by jasonw4331** [comment]
Can you provide more details? I'm unable to reproduce

**Comment by jasonw4331** [comment]
It might need reported to Customies

**Comment by IvanCraft623** [comment]
> Can you provide more details? I'm unable to reproduce

This was reproduced on a practically new server. As you can see in the crashdump the only two plugins were: SpectreZone and Customies

Steps:
1. Obtain a Specter Key
2. Use it for 5 seconds
3. Stop using it (You are teleported to what appears to be a room and immediately the server crashes.)

**Comment by IvanCraft623** [comment]
Have you been able to reproduce it?

**Comment by jasonw4331** [comment]
I haven't been able to reproduce it yet
