### ISSUE TITLE
Assertion `x < Base::ARRAY_DIM && y < Base::ARRAY_DIM && z < Base::ARRAY_DIM' failed.

### ISSUE THREAD

**Issue by PSYCHO1512** [jasonwynn10/SpectreZone#6]
When i use the key it gives this ---.3.1: ext/chunkutils2/lib/PalettedBlockArray.h:93: void PalettedBlockArray<BITS_PER_BLOCK, Block>::find(PalettedBlockArray<BITS_PER_BLOCK, Block>::Coord, PalettedBlockArray<BITS_PER_BLOCK, Block>::Coord, PalettedBlockArray<BITS_PER_BLOCK, Block>::Coord, short unsigned int&, unsigned char&) const [with VanillaPaletteSize BITS_PER_BLOCK = (VanillaPaletteSize)2; Block = unsigned int; PalettedBlockArray<BITS_PER_BLOCK, Block>::Coord = unsigned char]: Assertion `x < Base::ARRAY_DIM && y < Base::ARRAY_DIM && z < Base::ARRAY_DIM' failed. ---and restart the server

**Comment by VaxPex** [comment]
🐐

**Comment by jasonwynn10** [comment]
I'm unable to reproduce this bug. Can you supply any more information? @PSYCHO1512 @18780262934

**Comment by PSYCHO1512** [comment]
I will search for it when i get back to home

**Comment by PSYCHO1512** [comment]
And you using multiworld cause i had multiworld

**Comment by jasonwynn10** [comment]
According to Dylan this error is caused by an outdated php binary. Please update and let me know if you can still reproduce.
